### ISSUE TITLE
GUI not startting

### ISSUE THREAD

**Issue by disi** [lysannschlegel/RDAExplorer#1]
I run Windows 7 x64 and there is no GUI, the program would not start. Can you tell me if I need some special version of .NET or whatever you used?

Event log:
Application: RDAExplorerGUI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException
Stack:

I tried the updated .NET 4.6.1 and downloaded/installed 4.0 re-distributable, bot the same issue

**Comment by lysanntranvouez** [comment]
The application targets .NET Framework 4.5, so I'd expect that running it with 4.6.1 should work fine.

After some googling I have a suspicion... Can you please copy this file into the same directory as the .exe and try launching again: https://www.dropbox.com/s/kdl9bjx9notouex/RDAExplorerGUI.exe.config

**Comment by disi** [comment]
I did a quick test at home this morning and the same happens with the config in the folder. I also disconnected my second monitor and the same happens.
No error and no GUI, the process pops up in the task manager and closes shortly after, leaving the event log.

The current .NET version is now 4.5.2 after I uninstalled all of it, then deactivated 3.5.1, reinstalled 4.0 and let Windows patch itself.

Here at work it tells me I need .NET 4.5 to run the application, the machine is not updated regulary and still uses pure 4.0.

p.s. success! Here on my work machine it is fine now after I downloaded and installed MS .NET 4.6 with or without your extra config. My machine at home must have a .net issue. Sorry!

**Comment by lysanntranvouez** [comment]
Mh, I'm actually not entirely convinced. But as long as I can't reproduce this issue or get more information for debugging, there's not much I can do. In case there was more information in the event log, I would still like to see it, if you find the time to dig this up.
Also, does your work machine use Windows 7 too? Or could there be a difference here?

**Comment by disi** [comment]
I am good. In the meantime I changed to Windows 10 and it works fine here.
Really sorry, this was a problem with my system.
http://imgur.com/U5lqTkm

**Comment by lysanntranvouez** [comment]
Alright, thanks for clearing that up.
