### ISSUE TITLE
Anno 2205 Crash

### ISSUE THREAD

**Issue by GoldenLion78** [lysannschlegel/RDAExplorer#10]
`Hello,`
I have a problem with RDAExtract, and file.db create.
Extracting is ok, after change few data in xml file, for example, change only `<Value>100</Value>` to `<Value>200</Value>` the rda file size must be same. Game crash on start. Ok After creating file.db game not crash, but stop (freeze) after "Loading".
Then I try other version. Restore rda and file.db files from backup. I extract rda to folder Anno2205/data
and rewrite PreferLocalFiles false to true in engine.ini file. Game crash at start. Question, I must extract all rda files to /data folder? It is about 32GB :)
Sorry for my english.

**Comment by TheIpsin** [comment]
Normally you only need to extract the files you want to change

**Comment by lysanntranvouez** [comment]
The latest release ([1.4.0.0](https://github.com/lysannschlegel/RDAExplorer/releases/tag/v1.4.0.0)) should fix these problems.

I should point out that I haven't tested it with Anno 2205. I have however successfully started Anno 1800 after changing an rda file and generating a new file.db, and they both use the same format for file.db, as far as I can tell.

I will close this issue now, comment or create new issues if you have problems with the release.
