### ISSUE TITLE
Editing 1404 save game files

### ISSUE THREAD

**Issue by JayGraybeard** [lysannschlegel/RDAExplorer#11]
I love ANNO 1404. I am not a programmer. I don't really understand what I can do with RDAExplorer that would be helpful to me in the game. I am having a particularly hard time with one of the achievements and I am wondering if RDA can be used to edit a saved game file in ANNO 1404 - Venice. Specifically if it can be used to change the value of "time played".  I was able to extract files and change them but the saved game will no longer reload after that occurs. Thanks for any comments or insights.

**Comment by lysanntranvouez** [comment]
I haven’t worked with 1404 myself, but from what I recall from other players trying the same thing, the save game files have some anti cheat protection to prevent exactly what you are trying to do ;)

I don’t really have the time to investigate how that could be worked around.

I have more experience using it to mod the game. But once again, as soon as you do that achievements will be disabled. So you can’t really use it to change the conditions for how to get your achievement.

I suppose you’ll be stuck with trying to get it the old-fashioned way. All I can suggest is you try to google it and see what people recommend :woman_shrugging:

**Comment by JayGraybeard** [comment]
Thank you so much for the very quick response. I wasn't sure what to expect since I am at this point turning into a cheater due to pretty much exhausting everything else I've thought of so far to get the particular achievement I've been working on. Wasn't sure if you'd help a cheater. I've searched everywhere I can think of for other gamers' recommendations and suggestions. I'm just slow at certain aspects of the game. I will continue the old-fashion way as you mentioned. The achievement I'm after must be completed in 5 hours or less and a specific task I must do that is needed to win the achievement takes a minimum of 153 minutes to complete so the task must be started at the 147 minute mark or sooner in order to "win" the task. I bother to tell you this because this evening I worked on a game in which I was able to start the specific task at the 150 minute mark which is the closest I've gotten to at least starting the task within the correct time frame in my dozen or so tries. In my first attempt I didn't even have the specific task started after 5 hours of play so at least I'm making progress the old fashioned way. 
Thanks again for the quick response.
    On Sunday, February 10, 2019, 2:42:41 AM CST, Lysann Schlegel <notifications@github.com> wrote:  
 
 
I haven’t worked with 1404 myself, but from what I recall from other players trying the same thing, the save game files have some anti cheat protection to prevent exactly what you are trying to do ;)

I don’t really have the time to investigate how that could be worked around.

I have more experience using it to mod the game. But once again, as soon as you do that achievements will be disabled. So you can’t really use it to change the conditions for how to get your achievement.

I suppose you’ll be stuck with trying to get it the old-fashioned way. All I can suggest is you try to google it and see what people recommend

**Comment by JayGraybeard** [comment]
Hi L,
Using RDA Explorer and Note Pad++ I had in the past successfully created a mod for the PC game ANNO 1404. I am attempting to do a different mod but this time when I try to save the file I have made changes to (quests.xml) I get an error message stating that access is denied to the path to my patch0.rda file. I attached a copy of the message in a .PNG. I haven't been able to find any info on-line as to why I might be getting this message. Do you have any insight or suggestions as to what I'm dong wrong or why the file will not save?
Thanks ever so much.
John


    On Sunday, February 10, 2019, 2:42:41 AM CST, Lysann Schlegel <notifications@github.com> wrote:  
 
 
I haven’t worked with 1404 myself, but from what I recall from other players trying the same thing, the save game files have some anti cheat protection to prevent exactly what you are trying to do ;)

I don’t really have the time to investigate how that could be worked around.

I have more experience using it to mod the game. But once again, as soon as you do that achievements will be disabled. So you can’t really use it to change the conditions for how to get your achievement.

I suppose you’ll be stuck with trying to get it the old-fashioned way. All I can suggest is you try to google it and see what people recommend
