### ISSUE TITLE
Game crashes right at startup (where it says external deliveries...etc)

### ISSUE THREAD

**Issue by RSithu** [lysannschlegel/RDAExplorer#3]
I modified buildings (made rice farm(I think) farmfields cost 5 times to maintain and produce 5 times the original) in data13 data>config>game>asset>objects. I modded patch13 because it was last modified (by the tundra patch).

**Comment by MadManSK** [comment]
Hello.
I afraid that problem is with biger last update.. when you only unpack and pack back data13 and nothing change.. game will crash ..dosnt matter when some file change or no...

**Comment by lysannschlegel** [comment]
Thanks for pointing it out. I will look into this today.

**Comment by lysanntranvouez** [comment]
I uploaded a new release which should fix this issue: https://github.com/lysannschlegel/RDAExplorer/releases/tag/v1.2.1.0-beta.1

Please let me know if this works for you.

**Comment by MadManSK** [comment]
So all runing good now. Thank you.
