### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by hsshss2005** [lysannschlegel/RDAExplorer#4]
when i revisions game (anything), save done.and the game is Crash.
Can you upgrade the program, please

**Comment by hsshss2005** [comment]
My English is not good, please forgive me

**Comment by lysanntranvouez** [comment]
I'm taking a look right now.
I suspect it started breaking after the most recent game update?

**Comment by hsshss2005** [comment]
yes . my version is 1.7 . I try to use quickbms but it's not work. So I found it(RDAexplorer) on Google. This tool is cool, it can let me see

**Comment by hsshss2005** [comment]
Someone tell me, when packaged blocks will disorder .
Cause the modified files can not be read and they told me in these(data2，data13~16)file some blocks Used encryption
There is also a possibility, any modified will be file.db verification failed
Hope this helps some of you.
If the cause can not unpack because the encryption, please told me. Thanks.

**Comment by lysanntranvouez** [comment]
Unpacking should be fine, even for encrypted files, so you can look at the files, but you cannot save them.

I also suspect that file.db is the issue. I took a look at it, and now know that yes, changing positions in the rda files will probably break the game, unless file.db is also updated.
It will take a bit of time to implement that.

It's a bit weird because the file.db existed for some time, but it didn't break the game back then. Or maybe I was just lucky?

**Comment by hsshss2005** [comment]
I think file.db is used to check the integrity of the game . But I still have questions,I used a Chinese language pack I found that he could replace data0, data10, data11, data12 file without destroying game.
but i used RDAExplorer game is crash, i think the language pack used quickbms, I caught a exe file.
i try use the exe file unpacking encrypted files (data16) but it's not work, the exe.file will be crash

**Comment by lysanntranvouez** [comment]
Can you send me a link to this language pack? I think we could just extract the modified files and have the game load them. No need to change rda files:

---

If you just want to modify some game files, you don't have to save the rda files.
You can just extract the files you want to modify from the rda files using RDAExplorer and place them in `C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\games\Anno 2205` (this is where your maindata folder is).

So for instance I extracted the file
`data\config\game\credits.txt` in `data16.rda` to
`C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\games\Anno 2205\data\config\game\credits.txt`.
I then changed some text in there for testing and saved the file.

Now you just have to update your game settings to look in the data directory instead of just looking in maindata\*.rda:
You should have a file `C:\Users\<username>\Documents\Anno 2205\config\engine.ini`. Open it with a text editor, and change `PreferLocalFiles` from `false` to `true`.

Launch the game and open the credits (it's the middle one of the 3 small buttons in the main menu: settings, credits, exit).
Check that your changes to the credits are there.

This is how any game file could be modified without saving the rda file.

**Comment by hsshss2005** [comment]
I am very, very grateful this approach.
 we've checked the language pack, It is a bms script.It is completely different and rda explorer,quickbms using binary address offset modify the program. and Rdaexplorer unpack will be a new package So the process of packing what will not be recognized 
my friend fix this bms, it's work now,Perhaps some encryption not solved.But this should help you perfect for RdaExplorer
`

# Anno  2205 (script 0.1.3)

# script for QuickBMS http://quickbms.aluigi.org

quickbmsver "0.7.0"

getdstring SIGN 32
#print ("%SIGN%")
if SIGN & "Resource File V2.2"
    goto 0x310
    get FIRST_NEXT long
    #print ("%FIRST_NEXT%")
    math RES_FILE_TYPE = 2
    #print ("SIGN=%SIGN%") #"RES_FILE_TYPE =2.2"
else
    set SIGN unicode SIGN
    if SIGN & "Resource File"   # "Resource File V2.0"
        math FIRST_NEXT = 0x404
        math RES_FILE_TYPE = 1
    else
        print "Error: no magic signature found"
        cleanexit
    endif
endif

get FULLSIZE asize

for NEXT_OFF = FIRST_NEXT < FULLSIZE

```
goto NEXT_OFF
math OFFSET = NEXT_OFF

get TYPE long
get FILES long
#get CHEN long
#print "------For[0]TYPE=%TYPE% " 

if RES_FILE_TYPE <= 1
    get ZSIZE long
    get SIZE long
    get NEXT_OFF long
else

    get ZSIZE longlong
    get SIZE longlong
    get NEXT_OFF longlong

endif
math OFFSET -= ZSIZE

savepos BACKUP_OFFSET

# type & 4 uses a compressed container
# instead of single compressed files

# MEMORY_FILE   table of information
# MEMORY_FILE2  decompressed file system

if SIZE != 0
    if TYPE & 4
        math OFFSET -= 8
    endif

    # copy&paste except for the target file
    callfunction SET_ENCRYPTION 1
    if TYPE & 1
        clog MEMORY_FILE OFFSET ZSIZE SIZE
    else
        log MEMORY_FILE OFFSET ZSIZE
    endif
    encryption "" ""

    if TYPE & 4
        math TMP = OFFSET
        math TMP += ZSIZE
        goto TMP
        if RES_FILE_TYPE <= 1
            get ZSIZE long
            get SIZE long
        else
            get ZSIZE longlong
            get SIZE longlong
        endif
        math OFFSET -= ZSIZE

        callfunction SET_ENCRYPTION 1
        if TYPE & 1
            clog MEMORY_FILE2 OFFSET ZSIZE SIZE
        else
            log MEMORY_FILE2 OFFSET ZSIZE
        endif
        encryption "" ""
    endif

    for i = 0 < FILES
        getdstring NAME 0x208 MEMORY_FILE
        set NAME unicode NAME


        if RES_FILE_TYPE <= 1
            get OFFSET long MEMORY_FILE
            get ZSIZE long MEMORY_FILE
            get SIZE long MEMORY_FILE
            get CRC long MEMORY_FILE
            get ZERO long MEMORY_FILE
        else
            get OFFSET longlong MEMORY_FILE
            get ZSIZE longlong MEMORY_FILE
            get SIZE longlong MEMORY_FILE
            get CRC long MEMORY_FILE
            get ZERO long MEMORY_FILE
            get ZERO long MEMORY_FILE
            get ZERO long MEMORY_FILE
        endif

        if SIZE != 0
            if TYPE & 4
                log NAME OFFSET ZSIZE MEMORY_FILE2
            else
                callfunction SET_ENCRYPTION 1
                if TYPE & 1
                    clog NAME OFFSET ZSIZE SIZE
                else
                    log NAME OFFSET ZSIZE
                endif
                encryption "" ""
            endif
        endif
    next i

    goto BACKUP_OFFSET
endif
```

next

startfunction SET_ENCRYPTION
    # Crypt "34AT9fdY33uT16m7" is used for signature in 2070
    if TYPE & 2
        #print "TYPE=2 and files=%FILES%"
        if RES_FILE_TYPE >= 2
            #print "2205 can Encrypte to do and files=%FILES%"
            #encryption random "5 666666" 16    # not valid because needs >>16 on xor!
            math KEY = 0x71C71C71
            putvarchr MEMORY_FILE3 ZSIZE 0 short
            log MEMORY_FILE3 0 0
            math TMPSZ = ZSIZE
            math TMPSZ / 2
            math TMPSZ \* 2
            for x = 0 < TMPSZ
                math KEY \* 214013
                math KEY + 2531011
                math TMP = KEY
                math TMP >> 16
                math TMP & 0x7fff
                putvarchr MEMORY_FILE3 x TMP short
            next x + 2
                putvarchr MEMORY_FILE3 x 0 short # padding
            getdstring XOR_KEY ZSIZE MEMORY_FILE3   # wastes some memory
            encryption xor XOR_KEY "" 0 ZSIZE

```
    else

        #encryption random "5 666666" 16    # not valid because needs >>16 on xor!
        math KEY = 666666
        putvarchr MEMORY_FILE3 ZSIZE 0 short
        log MEMORY_FILE3 0 0
        math TMPSZ = ZSIZE
        math TMPSZ / 2
        math TMPSZ * 2
        for x = 0 < TMPSZ
            math KEY * 0x000343fd
            math KEY + 0x00269ec3
            math TMP = KEY
            math TMP >> 16
            math TMP & 0x7fff
            putvarchr MEMORY_FILE3 x TMP short
        next x + 2
            putvarchr MEMORY_FILE3 x 0 short # padding
        getdstring XOR_KEY ZSIZE MEMORY_FILE3   # wastes some memory
        encryption xor XOR_KEY "" 0 ZSIZE
    endif
endif
```

endfunction

`

**Comment by lysanntranvouez** [comment]
As of version 1.3 there is now an additional tool that can be used to re-generate file.db after modifying an *.rda file. This will ensure that the game runs even with modified *.rda files.

See the [release notes for version 1.3.0.0](https://github.com/lysannschlegel/RDAExplorer/releases/tag/v1.3.0.0) for more information.
