### ISSUE TITLE
Unable to load DLL 'zlib.DLL'

### ISSUE THREAD

**Issue by xkvnn** [lysannschlegel/RDAExplorer#5]
I try open any file rda of ANNO 1404 and get error:
Unable to load DLL 'zlib.DLL': The specified module could not be found. (Exception from HRESULT: 0x8007007E

**Comment by ExplosionGuy** [comment]
Exactly the same problem I have.

**Comment by lysanntranvouez** [comment]
Thanks for reporting this issue!
I updated the release zip to include the missing file. Please try [downloading the latest release](https://github.com/lysannschlegel/RDAExplorer/releases) again.

**Comment by ExplosionGuy** [comment]
Thank you! Great mods!

**Comment by xkvnn** [comment]
Thank you!
