### ISSUE TITLE
CTD when trying to extract a directory.

### ISSUE THREAD

**Issue by hhrhhr** [lysannschlegel/RDAExplorer#8]
Сhecked on 1404 and 2205. Open .rda, select any directory (data/config, for example), right-click, "Extract", select path -> crash.

**Comment by lysanntranvouez** [comment]
Thanks for reporting!

This should be fixed now on the latest release: https://github.com/lysannschlegel/RDAExplorer/releases/tag/v1.3.1.0.

Please reopen if the fix doesn't work for you.
